from enum import Enum

class CMD(Enum):
    PING = 0
    START_RECORD = 1
    STOP_ROBOT = 2
    SEND_LOG = 3
    SET_DURATION=4
    SET_MODE=5
    SET_MOTOR_SCALE=6
    SET_FLIP_DURATION=7
    UPDATE_DIST_PID=8
    UPDATE_ORIENT_PID=9
    SET_DIST_SETPOINT=10
    SET_ORIENT_SETPOINT=11,
    SET_NAV_SETPOINTS=12
    SET_DIST_SENSOR_MODE=13